# Generated by Django 4.1.1 on 2022-09-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
    ]
