# Generated by Django 4.1.1 on 2022-09-14 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0002_remove_product_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
    ]
