# Generated by Django 4.1.1 on 2022-09-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0003_remove_cart_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
