# Generated by Django 4.1.1 on 2022-09-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0004_cart_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
