# Generated by Django 4.1.1 on 2022-09-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0005_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.IntegerField(null=True),
        ),
    ]
