# Generated by Django 4.1.1 on 2022-09-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0007_alter_cart_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
    ]
