# Generated by Django 4.1.1 on 2022-09-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0008_remove_cart_cart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
