# Generated by Django 4.1.1 on 2022-09-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0013_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.TextField(),
        ),
    ]
